services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./manager/mqtt-config.conf:/mosquitto/config/mosquitto.conf
  temperature_room_1:
    build: 
      context: .
      dockerfile: ./sensors/temperature/Dockerfile
    environment:
      - UUID=${SENSOR_UUID_TEMPERATURE_1}
      - ROOM_ID=1
    depends_on:
      - mqtt_broker
  humidity_room_1:
    build: 
      context: .
      dockerfile: ./sensors/humidity/Dockerfile
    environment:
      - UUID=${SENSOR_UUID_HUMIDITY_1}
      - ROOM_ID=1
    depends_on:
      - mqtt_broker
  light_level_room_1:
    build: 
      context: .
      dockerfile: ./sensors/light_level/Dockerfile
    environment:
      - UUID=${SENSOR_UUID_LIGHT_LEVEL_1}
      - ROOM_ID=1
    depends_on:
      - mqtt_broker
  movement_room_1:
    build: 
      context: .
      dockerfile: ./sensors/movement/Dockerfile
    environment:
      - UUID=${SENSOR_UUID_MOVEMENT_1}
      - ROOM_ID=1
    depends_on:
      - mqtt_broker
  temperature_room_2:
    build: 
      context: .
      dockerfile: ./sensors/temperature/Dockerfile
    environment:
      - UUID=${SENSOR_UUID_TEMPERATURE_2}
      - ROOM_ID=2
    depends_on:
      - mqtt_broker
  humidity_room_2:
    build: 
      context: .
      dockerfile: ./sensors/humidity/Dockerfile
    environment:
      - UUID=${SENSOR_UUID_HUMIDITY_2}
      - ROOM_ID=2
    depends_on:
      - mqtt_broker
  light_level_room_2:
    build: 
      context: .
      dockerfile: ./sensors/light_level/Dockerfile
    environment:
      - UUID=${SENSOR_UUID_LIGHT_LEVEL_2}
      - ROOM_ID=2
    depends_on:
      - mqtt_broker
  movement_room_2:
    build:
      context: .
      dockerfile: ./sensors/movement/Dockerfile
    environment:
      - UUID=${SENSOR_UUID_MOVEMENT_2}
      - ROOM_ID=2
    depends_on:
      - mqtt_broker
  vent_room_1:
    build:
      context: .
      dockerfile: ./activators/vent/Dockerfile
    environment:
      - UUID=${ACTIVATOR_UUID_VENT_1}
      - ROOM_ID=1
    depends_on:
      - mqtt_broker
  vent_room_2:
    build:
      context: .
      dockerfile: ./activators/vent/Dockerfile
    environment:
      - UUID=${ACTIVATOR_UUID_VENT_2}
      - ROOM_ID=2
    depends_on:
      - mqtt_broker
  heater_room_1:
    build:
      context: .
      dockerfile: ./activators/heater-air-con/Dockerfile
    environment:
      - UUID=${ACTIVATOR_UUID_HEATER_1}
      - ROOM_ID=1
    depends_on:
      - mqtt_broker
  heater_room_2:
    build:
      context: .
      dockerfile: ./activators/heater-air-con/Dockerfile
    environment:
      - UUID=${ACTIVATOR_UUID_HEATER_2}
      - ROOM_ID=2
    depends_on:
      - mqtt_broker
  alarm_room_1:
    build:
      context: .
      dockerfile: ./activators/alarm/Dockerfile
    environment:
      - UUID=${ACTIVATOR_UUID_ALARM_1}
      - ROOM_ID=1
    depends_on:
      - mqtt_broker
  alarm_room_2:
    build:
      context: .
      dockerfile: ./activators/alarm/Dockerfile
    environment:
      - UUID=${ACTIVATOR_UUID_ALARM_2}
      - ROOM_ID=2
    depends_on:
      - mqtt_broker
  light_room_1:
    build:
      context: .
      dockerfile: ./activators/light/Dockerfile
    environment:
      - UUID=${ACTIVATOR_UUID_LIGHT_1}
      - ROOM_ID=1
    depends_on:
      - mqtt_broker
  light_room_2:
    build:
      context: .
      dockerfile: ./activators/light/Dockerfile
    environment:
      - UUID=${ACTIVATOR_UUID_LIGHT_2}
      - ROOM_ID=2
    depends_on:
      - mqtt_broker
  manager:
    build:
      context: .
      dockerfile: manager/Dockerfile
    ports:
    - "3000:3000"
    - "8765:8765"
    depends_on:
      - mqtt_broker
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    build:
      context: ./smartHome_app
    container_name: smarthome_frontend
    depends_on:
      - manager
    ports:
      - "8080:80"
    volumes:
      - ./smartHome_app:/usr/share/nginx/html
    restart: always
volumes:
  db_data: